adding common and preparing page people
KubaTuta/Movie-Browser pull request #10
Opened 2023-03-23 14:39 UTC by Mateusszzp

Please, did I understand my task correctly added page with popular people without navigation connected to API

2023-03-23 17:12 UTC, KubaTuta requested changes
yep, you should mapped only 1 tile on api or at least at exapmple api from /public

2023-03-23 17:51 UTC, Mateusszzp commented
> yep, you should mapped only 1 tile on api or at least at exapmple api from /public

hey, it seems to me that it is made so universally that it can be added as needed and downloaded from the api

2023-03-23 19:56 UTC, HaniaNassalska commented on src/store.js
> +    popularPeople: popularPeopleReduser,
I think it should be popularPeopleReducer :)

2023-03-23 19:58 UTC, HaniaNassalska approved these changes

2023-03-24 14:36 UTC, Mateusszzp commented on src/store.js
> +    popularPeople: popularPeopleReduser,
Yes you are right, I agree with you 100%.

2023-03-25 07:49 UTC, closed without merging