Hania tile
KubaTuta/Movie-Browser pull request #2
Opened 2023-03-16 00:02 UTC by HaniaNassalska

2023-03-16 11:14 UTC, KubaTuta requested changes
looks great so far

2023-03-16 11:14 UTC, KubaTuta commented on src/Features/Movies/Tile/styled.js
> +width: 324px;
i think is better to set this to 100%, so it leaves gaps between tiles same at different screen sizes

2023-03-16 11:14 UTC, KubaTuta commented on src/Features/Movies/examplePopularMovies.json
> -      "release_date": "2022-12-07",
I believe it was non intented:)

2023-03-16 11:14 UTC, KubaTuta commented on src/Features/Movies/index.js
> +          </Tile>
definately separate component

2023-03-16 11:14 UTC, KubaTuta commented on src/Features/Movies/Tile/styled.js
remember to use @media for mobiles

2023-03-16 11:48 UTC, HaniaNassalska commented on src/Features/Movies/Tile/styled.js
> +width: 324px;
ok

2023-03-16 11:48 UTC, HaniaNassalska commented on src/Features/Movies/examplePopularMovies.json
> -      "release_date": "2022-12-07",
It was :) - because it generates a different view of tile. I wanted to see what it would look like without date. Look at the Figma.

2023-03-16 11:48 UTC, HaniaNassalska commented on src/Features/Movies/index.js
> +          </Tile>
Of course it will be. I wrote earlier -  pull request  was only to practice and to help you in your works. I will finish it this evening (I hope).

2023-03-16 11:48 UTC, HaniaNassalska commented on src/Features/Movies/Tile/styled.js
Same as I wrote above.

2023-03-18 09:12 UTC, KubaTuta approved these changes
awesome, movies page 1 api works great! tile almost perfect

2023-03-18 09:12 UTC, merged